version: "3.8"

services:
  #compose grafana
  image-renderer:
    container_name: image-renderer
    env_file: image-renderer.env
    deploy:
      restart_policy:
        condition: always
        delay: 5s
    image: grafana/grafana-image-renderer:latest
    labels:
      com.centurylinklabs.watchtower.enable: "true"
      traefik.enable: "false"

networks:
  default:
    external: true
    name: $NETWORK
